# Generated by Django 6.0.6 on 2026-06-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('annual', 'Annual Report'), ('audit', 'Audited Statement'), ('impact', 'Impact Report')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='reports/')),
                ('year', models.PositiveIntegerField()),
                ('published_at', models.DateField()),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', '-published_at'],
            },
        ),
    ]
